databases:
  - name: catcollectordb
    plan: free
    databaseName: catcollector
    user: catcollector

services:
  - type: web
    plan: free
    name: catcollector
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python3 -m gunicorn catcollector.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: catcollectordb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4